// Generated by tools/build_survey.py. Edit the questions there, then rebuild.
window.SURVEY = [
 {
  "key": "Students",
  "title": "Students (secondary school and university)",
  "intro": "About your school or campus canteen lunch. Takes about 4 minutes. Anonymous.",
  "sheet": "Students_Data",
  "questions": [
   {
    "code": "S1",
    "text": "Which are you?",
    "type": "cat",
    "options": [
     "Secondary school",
     "University"
    ]
   },
   {
    "code": "S2",
    "text": "How often do you leave food on your tray?",
    "type": "cat",
    "options": [
     "Never",
     "Rarely",
     "Sometimes",
     "Often",
     "Almost always"
    ]
   },
   {
    "code": "S3",
    "text": "What is the main reason you leave food?",
    "type": "cat",
    "options": [
     "Portion too big",
     "Don’t like the taste",
     "Not hungry",
     "Ran out of time",
     "Didn’t recognise the dish"
    ]
   },
   {
    "code": "S4",
    "text": "Would you take a smaller portion if you could ask for one easily?",
    "type": "cat",
    "options": [
     "Yes",
     "Maybe",
     "No"
    ]
   },
   {
    "code": "S5",
    "text": "Are you told to finish everything on your plate?",
    "type": "cat",
    "options": [
     "Yes",
     "Sometimes",
     "No"
    ]
   },
   {
    "code": "S6",
    "text": "I would like to see what I ate at lunch (food groups and nutrients).",
    "type": "lik",
    "options": [
     "Strongly disagree",
     "Strongly agree"
    ]
   },
   {
    "code": "S7",
    "text": "Which would you rather see about your lunch?",
    "type": "cat",
    "options": [
     "Food groups",
     "Calories",
     "Both",
     "Neither"
    ]
   },
   {
    "code": "S8",
    "text": "I would scan my tray before and after lunch if it fed a virtual pet.",
    "type": "lik",
    "options": [
     "Strongly disagree",
     "Strongly agree"
    ]
   },
   {
    "code": "S9",
    "text": "A weekly class competition on food waste would motivate me.",
    "type": "lik",
    "options": [
     "Strongly disagree",
     "Strongly agree"
    ]
   },
   {
    "code": "S10",
    "text": "I would be comfortable signing in to a scanner with my face.",
    "type": "lik",
    "options": [
     "Strongly disagree",
     "Strongly agree"
    ]
   },
   {
    "code": "S11",
    "text": "Anything else about lunch or food waste at your canteen?",
    "type": "text",
    "options": null
   }
  ]
 },
 {
  "key": "Kitchen",
  "title": "Canteen and kitchen staff",
  "intro": "About how your canteen plans food and handles leftovers. Takes about 4 minutes.",
  "sheet": "Kitchen_Data",
  "questions": [
   {
    "code": "K1",
    "text": "What is your role?",
    "type": "cat",
    "options": [
     "Canteen operator",
     "Cook",
     "Kitchen assistant"
    ]
   },
   {
    "code": "K2",
    "text": "How do you mainly decide how much to cook each day?",
    "type": "cat",
    "options": [
     "Past experience",
     "Headcount × standard portion",
     "Previous day’s leftovers",
     "Written records"
    ]
   },
   {
    "code": "K3",
    "text": "Roughly what percentage of the food you cook is thrown away on a typical day?",
    "type": "num",
    "options": null
   },
   {
    "code": "K4",
    "text": "Do you know which dishes come back on trays most?",
    "type": "cat",
    "options": [
     "Yes, accurately",
     "Roughly",
     "No"
    ]
   },
   {
    "code": "K5",
    "text": "How often do you prepare more food than is eaten?",
    "type": "cat",
    "options": [
     "Never",
     "Rarely",
     "Weekly",
     "Several times a week",
     "Daily"
    ]
   },
   {
    "code": "K6",
    "text": "A suggested order for tomorrow, based on what was eaten, would be useful.",
    "type": "lik",
    "options": [
     "Not useful",
     "Very useful"
    ]
   },
   {
    "code": "K7",
    "text": "Seeing waste broken down by dish would be useful.",
    "type": "lik",
    "options": [
     "Not useful",
     "Very useful"
    ]
   },
   {
    "code": "K8",
    "text": "A monthly carbon report would be useful.",
    "type": "lik",
    "options": [
     "Not useful",
     "Very useful"
    ]
   },
   {
    "code": "K9",
    "text": "How many minutes a day do you spend planning orders and quantities?",
    "type": "num",
    "options": null
   },
   {
    "code": "K10",
    "text": "I am worried a new system would add to my workload.",
    "type": "lik",
    "options": [
     "Strongly disagree",
     "Strongly agree"
    ]
   },
   {
    "code": "K11",
    "text": "Anything else?",
    "type": "text",
    "options": null
   }
  ]
 },
 {
  "key": "Hospital",
  "title": "Hospital staff (nurses, dietitians, ward managers)",
  "intro": "About how patients’ food intake is tracked on your ward. Takes about 4 minutes.",
  "sheet": "Hospital_Data",
  "questions": [
   {
    "code": "H1",
    "text": "What is your role?",
    "type": "cat",
    "options": [
     "Nurse",
     "Dietitian",
     "Ward manager"
    ]
   },
   {
    "code": "H2",
    "text": "How is patients’ food intake mainly tracked on your ward?",
    "type": "cat",
    "options": [
     "Food charts",
     "Visual estimate",
     "Patient report",
     "Not tracked"
    ]
   },
   {
    "code": "H3",
    "text": "I am confident our intake records are accurate.",
    "type": "lik",
    "options": [
     "Strongly disagree",
     "Strongly agree"
    ]
   },
   {
    "code": "H4",
    "text": "How many minutes per shift do you spend documenting food intake?",
    "type": "num",
    "options": null
   },
   {
    "code": "H5",
    "text": "How quickly is a patient who stops eating usually noticed?",
    "type": "cat",
    "options": [
     "Same day",
     "After 2–3 days",
     "After 4+ days",
     "Often missed"
    ]
   },
   {
    "code": "H6",
    "text": "What is the most common reason patients leave food?",
    "type": "cat",
    "options": [
     "Poor appetite",
     "Taste",
     "Portion too big",
     "Too tired",
     "Pain or nausea"
    ]
   },
   {
    "code": "H7",
    "text": "Automatic intake records for every tray would be useful.",
    "type": "lik",
    "options": [
     "Not useful",
     "Very useful"
    ]
   },
   {
    "code": "H8",
    "text": "An alert that includes the patient’s reason for not eating would be useful.",
    "type": "lik",
    "options": [
     "Not useful",
     "Very useful"
    ]
   },
   {
    "code": "H9",
    "text": "Would patients benefit from choosing their next day’s meals and portion size?",
    "type": "cat",
    "options": [
     "Yes",
     "Maybe",
     "No"
    ]
   },
   {
    "code": "H10",
    "text": "Anything else?",
    "type": "text",
    "options": null
   }
  ]
 },
 {
  "key": "Office",
  "title": "Office workers",
  "intro": "About lunch at your workplace canteen. Takes about 4 minutes. Anonymous.",
  "sheet": "Office_Data",
  "questions": [
   {
    "code": "O1",
    "text": "Your age group",
    "type": "cat",
    "options": [
     "20–29",
     "30–39",
     "40–49",
     "50+"
    ]
   },
   {
    "code": "O2",
    "text": "How many days a week do you eat at the office canteen?",
    "type": "num",
    "options": null
   },
   {
    "code": "O3",
    "text": "Do you have a health goal for your meals?",
    "type": "cat",
    "options": [
     "Lose weight",
     "Build muscle",
     "Steady energy",
     "Eat balanced",
     "None"
    ]
   },
   {
    "code": "O4",
    "text": "I know the nutrients in my canteen lunch.",
    "type": "lik",
    "options": [
     "Strongly disagree",
     "Strongly agree"
    ]
   },
   {
    "code": "O5",
    "text": "How often do you feel an energy dip in the afternoon?",
    "type": "cat",
    "options": [
     "Never",
     "Rarely",
     "Sometimes",
     "Often",
     "Daily"
    ]
   },
   {
    "code": "O6",
    "text": "Would you pre-order lunch to skip the queue?",
    "type": "cat",
    "options": [
     "Yes",
     "Maybe",
     "No"
    ]
   },
   {
    "code": "O7",
    "text": "A daily lunch suggestion for my health goal would be useful.",
    "type": "lik",
    "options": [
     "Not useful",
     "Very useful"
    ]
   },
   {
    "code": "O8",
    "text": "Would you share your meal data with your employer?",
    "type": "cat",
    "options": [
     "Yes",
     "Only anonymous totals",
     "No"
    ]
   },
   {
    "code": "O9",
    "text": "How many minutes do you usually queue at lunch?",
    "type": "num",
    "options": null
   },
   {
    "code": "O10",
    "text": "Anything else?",
    "type": "text",
    "options": null
   }
  ]
 }
];
